var quizData = {
  title: "Which New York City Animal Decapitator Are You?",
  subtitle: "Find out which decapitator from the Useless Press Decapitated Animal Dataset you are.",
  questions: [
    {
      question: "images/q1/title.png",
      answers: [
        {id: 1, someshit: "images/q1/1.png"},
        {id: 2, someshit: "images/q1/2.png"},
        {id: 3, someshit: "images/q1/3.png"},
        {id: 4, someshit: "images/q1/4.png"},
        {id: 5, someshit: "images/q1/5.png"},
        {id: 6, someshit: "images/q1/6.png"},
      ]
    },
    {
      question: "images/q2/title.png",
      answers: [
        {id: 1, someshit: "images/q2/1.png"},
        {id: 2, someshit: "images/q2/2.png"},
        {id: 3, someshit: "images/q2/3.png"},
        {id: 4, someshit: "images/q2/4.png"},
        {id: 5, someshit: "images/q2/5.png"},
        {id: 6, someshit: "images/q2/6.png"},
      ]
    },
    {
      question: "images/q3/title.png",
      answers: [
        {id: 1, someshit: "images/q3/1.png"},
        {id: 2, someshit: "images/q3/2.png"},
        {id: 3, someshit: "images/q3/3.png"},
        {id: 4, someshit: "images/q3/4.png"},
        {id: 5, someshit: "images/q3/5.png"},
        {id: 6, someshit: "images/q3/6.png"},
      ]
    },
    {
      question: "images/q4/title.png",
      answers: [
        {id: 1, someshit: "images/q4/1.png"},
        {id: 2, someshit: "images/q4/2.png"},
        {id: 3, someshit: "images/q4/3.png"},
        {id: 4, someshit: "images/q4/4.png"},
        {id: 5, someshit: "images/q4/5.png"},
        {id: 6, someshit: "images/q4/6.png"},
      ]
    },
  ],
  outcomes: [
    {
      solution: [4,5,3,1],
      output: "Voodoo Chicken Leg Person",
      image: "images/results/bagvoodoo.png",
      rawData: {
        animal:"Birds",
        quantity:1,
        body_part_found:"Head, Legs, Body parts separated",
        date_started:"4/1/2006",
        date_closed:"4/1/2006",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Manhattan",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"THE CALLER IS REPORTING THAT THERE ARE 5 BLACK BAG FILLED WITGH DEAD BIRDS CHICKEN LEGS OR ROOSTER LEGS AND THE BIRDS HAVE NAILS IN THEIR HEAD LIKE SOMEONE WAS DOING VOODOO. THIS IS NOT THE FIRST TIME THECALLER HAS REPORTED THIS. THE BAG IS INSIDE THE PARK ON THE 90 STREET ENTRANCE WITH THE WALKWAY SPLITS BY A TREE THE BAGS ARE NEXT TO IT.",
        location_type:"Park",
        park_or_facility:"RIVERSIDE PARK - HIPPO PLAYGROUND",
        property_number:"M071",
        park_district:"14",
        additional_location_details:"ON THE 90 STREET ENTRANCE TAKE THE RIGHT HAND PATH WALK 100 YARD WITH THE PATH SPLIT THERE IS A BIG TREE WITH THE BAGS NEXT TO IT.",
        council_district_number:6,
        site_street_address:"W 91 ST AND RIVERSIDE DR",
        site_borough: "MANHATTAN",
        site_city_zip:"NEW YORK 10023",
        lat:40.7927426,
        lng:-73.9770935,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"4/1/2006",
        resolution_description:"The Department of Parks and Recreation has completed the requested work order and corrected the problem.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [1,3,5,2],
      output: "Cat Head on a Fence Person",
      image: "images/results/catfence.png",
      rawData: {
        animal:"Cat",
        quantity:1,
        body_part_found:"Head",
        date_started:"9/17/2007",
        date_closed:"11/13/2007",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Manhattan",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"CALLER STATED THAT THERE IS A CAT HEAD THAT IS ATTACHED TO STAKE THAT IS FENCED AROUND THE FIREMEN MEMORIAL.",
        location_type:"Park",
        park_or_facility:"RIVERSIDE PARK",
        property_number:"",
        park_district:"",
        additional_location_details:"FIREMEN MEMORIAL AREA. WALK ON THE PATH",
        council_district_number:9,
        site_street_address:"",
        site_borough:"MANHATTAN",
        site_city_zip:"NEW YORK 10025",
        lat:40.8012339,
        lng:-73.9723096,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"11/13/2007 16:26:26",
        resolution_description:"The Department of Parks and Recreation has completed the requested work order and corrected the problem.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [4,4,2,3],
      output: "Money Séance Bird Person",
      image: "images/results/moneybirds.png",
      rawData: {
        animal:"Dove & Chicken",
        quantity:2,
        body_part_found:"Head and Body",
        date_started:"11/11/2006",
        date_closed:"",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Bronx",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"CALLER STATES THAT HE WAS WALKING IN PELHAM BAY PARK IN THE BRONX, AND SAW A DEAD DOVE AND CHICKEN. THEY WERE SURROUNDED BY CANDLES AND COINS. THE ANIMALS WERE BEHEADED.",
        location_type:"Park",
        park_or_facility:"PELHAM BAY PARK - AILEEN RYAN RECREATION",
        property_number:"X039",
        park_district:"15",
        additional_location_details:"THE BIRDS IN THE WOODED AREA NEAR THE WOODS ENTRANCE AT STADIUM AVENUE AND MIDDLETOWN ROAD.",
        council_district_number:13,
        site_street_address:"(S) MIDDLETOWN RD. TO (W) BRUCKNER",
        site_borough:"BRONX",
        site_city_zip:"BRONX 10461",
        lat:40.8476284,
        lng:-73.8360251,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"",
        resolution_description:"The Department of Parks and Recreation usually requires 7 days to respond to this type of complaint. Please note your Service Request number for future reference.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [3,2,4,4],
      output: "Beheaded Some Turtles Person",
      image: "images/results/turtles.png",
      rawData: {
        animal:"Turtle",
        quantity:1,
        body_part_found:"Body Without Head",
        date_started:"4/24/2008",
        date_closed:"4/24/2008",
        source:"Department of Parks and Recreation",
        division:"Borough Maintenance Operations Office - Queens",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"PS2 J BROPHY RPTS THAT THERE ARE SOME TURTLES WITH MISSING HEAD.",
        location_type:"Park",
        park_or_facility:"CAPT TILLY PARK",
        property_number:"Q052",
        park_district:"8",
        additional_location_details:"HIGHLAND AVE OFF 164 STREET",
        council_district_number:24,
        site_street_address:"HIGHLAND AVE, UPLAND PKWY, GOTHIC PKWY",
        site_borough:"QUEENS",
        site_city_zip:"JAMAICA 11436",
        lat:40.7138051,
        lng:-73.7956131,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"4/24/2008 15:59:09",
        resolution_description:"Upon inspection the reported condition was not found, and, therefore, no action was taken.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [5,6,3,5],
      output: "Yummy Goat Ribs Person",
      image: "images/results/ribcage.png",
      rawData: {
        animal:"Goat, Rooster and Other animals",
        quantity:2,
        body_part_found:"Goat's Head & Rib Cage, Other body parts of other animals.",
        date_started:"4/18/2009",
        date_closed:"4/21/2009",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Queens",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"CALLER STATES: FOUND A GOATS HEAD, A BLACK ROOSTER AND SOME OTHER BODY PARTS OF ANIMALS. THERE IS ALSO A BIG RIB CAGE OF THE GOATS WITHOUT ANY MEAT ON IT.",
        location_type:"Park",
        park_or_facility:"FOREST PARK",
        property_number:"",
        park_district:"",
        additional_location_details:"ENTER PARK LANE SOUTH AND MYRTLE. ITS ON THE ORANGE TRAIL AND CALLER DOESN'T MIND TO COME OUT AND SHOW THE EVIDENCE.",
        council_district_number:30,
        site_street_address:"",
        site_borough:"QUEENS",
        site_city_zip:"RICHMOND HILL 11418",
        lat:40.6998251,
        lng:-73.8312457,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"4/21/2009 9:34:18",
        resolution_description:"The Department of Parks and Recreation has completed the requested work order and corrected the problem.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [6,2,6,6],
      output: "Goat Head Bowl Person",
      image: "images/results/goatbowl.png",
      rawData: {
        animal:"Goat",
        quantity:1,
        body_part_found:"Head",
        date_started:"9/28/2013",
        date_closed:"9/30/2013",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Brooklyn",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"ITS A GOAT HEAD IN A BOWL WITH FEATHERS AROUND AT THE ENTRANCE OF THIS PARK",
        location_type:"Park",
        park_or_facility:"PROSPECT PARK - GARFIELD TOT LOT",
        property_number:"B073-02D",
        park_district:"319",
        additional_location_details:"AT THE GARFIELD STREET AND PROSPECT PARK WEST ENTRANCE",
        council_district_number:39,
        site_street_address:"WEST DRIVE OPPOSITE GARFIELD PLACE",
        site_borough:"BROOKLYN",
        site_city_zip:"BROOKLYN 11215",
        lat:40.6734667,
        lng:-73.9794251,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"9/30/2013 16:24:26",
        resolution_description:"The Department of Parks and Recreation has completed the requested work order and corrected the problem.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [5,1,2],
      output: "Keep The Goat Body Warm And Separate From The Head Person",
      image: "images/results/treegoat.png",
      rawData: {
        animal:"Goat (Unsure)",
        quantity:1,
        body_part_found:"Head and Body",
        date_started:"1/2/2014",
        date_closed:"1/10/2014",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Manhattan",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"THERE IS A DEAD ANIMAL (MAYBE A GOAT) THAT WAS BEHEADED AND THE HEAD OF THE ANIMAL IS PINNED UP ON ONE OF THE TREES ABOUT 100 FEET INSIDE OF THE CHILDREN'S PLAYGROUND. THE BODY OF THE ANIMAL IS WRAPPED IN A RED SHEET AND ON THE GROUND.",
        location_type:"Park",
        park_or_facility:"HIGHBRIDGE PARK - FORT GEORGE",
        property_number:"M037-09",
        park_district:"112A",
        additional_location_details:"ABOUT 100 FEET WITHIN THE ENTRANCE",
        council_district_number:7,
        site_street_address:"FORT GEORGE AND SAINT NICHOLAS AVENUES",
        site_borough:"MANHATTAN",
        site_city_zip:"NEW YORK 10039",
        lat:40.8567322,
        lng:-73.9283922,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"1/10/2014 10:17:03",
        resolution_description:"The Department of Parks and Recreation has completed the requested work order and corrected the problem.",
        time_to_action:"Closed: No Further Updates"
      }
    },
    {
      solution: [2,1,3],
      output: "Chill Pig Head On The Beach Person",
      image: "images/results/beachpig.png",
      rawData:  {
        animal:"Pig",
        quantity:1,
        body_part_found:"Head",
        date_started:"7/8/2014",
        date_closed:"7/10/2014",
        source:"3-1-1 Call Center",
        division:"Borough Maintenance Operations Office - Bronx",
        form:"DPR General Intake",
        status:"Closed",
        priority:"Normal",
        complaint_type:"Animal in a Park",
        descriptor_1:"Dead Animal",
        descriptor_2:"N/A",
        complaint_details:"THERE IS A PIG'S HEAD AT THIS LOCATION. THE HEAD IS IN BETWEEN THE ROCKS, ON THE BEACH KILROE BEACH.",
        location_type:"Park",
        park_or_facility:"PELHAM BAY PARK",
        property_number:"",
        park_district:"",
        additional_location_details:"BEHIND THE BASKET BALL COURT",
        council_district_number:13,
        site_street_address:"",
        site_borough:"BRONX",
        site_city_zip:"BRONX 10464",
        lat:40.8615,
        lng:-73.7972,
        complaint_type_confirmed:"Animal in a Park",
        descriptor_confirmed:"Dead Animal",
        resolution_action_updated:"7/10/2014 8:20:09",
        resolution_description:"The Department of Parks and Recreation has inspected the situation in question and determined that the issue is out of its jurisdiction.",
        time_to_action:"Closed: No Further Updates"
      }
    }
  ]
}
